"""
Interactive CLI command to help users get started with Driftbase.
Guides through framework selection and generates copy-paste code snippets.
"""

from __future__ import annotations

import os
from pathlib import Path

import click
from driftbase.cli._deps import safe_import_rich

# Lazy import of rich dependencies
Console, Panel, Table = safe_import_rich()


def _get_code_snippet(framework: str, version: str, agent_function: str) -> str:
    """Generate framework-specific code snippet."""

    if framework == "langchain":
        return f"""from driftbase.integrations import LangChainTracer

# Create the tracer with your version
tracer = LangChainTracer(version='{version}')

# Pass it to your chain via callbacks
result = your_chain.invoke(
    input_data,
    config={{'callbacks': [tracer]}}
)"""

    elif framework == "langgraph":
        return f"""from driftbase.integrations import LangGraphTracer

# Create the tracer with your version
tracer = LangGraphTracer(version='{version}')

# Pass it to your graph via callbacks
result = your_graph.invoke(
    input_data,
    config={{'callbacks': [tracer]}}
)"""

    elif framework == "openai":
        return f"""from driftbase.integrations import OpenAITracer
from openai import OpenAI

client = OpenAI()

# Use the tracer as a context manager
with OpenAITracer(version='{version}'):
    response = client.chat.completions.create(
        model="gpt-4",
        messages=[{{"role": "user", "content": "Hello"}}]
    )"""

    elif framework == "autogen":
        return f"""from driftbase.integrations import AutoGenTracer
from autogen import AssistantAgent, UserProxyAgent

# Create the tracer
tracer = AutoGenTracer(version='{version}')

# Create your agent
assistant = AssistantAgent(name="assistant", llm_config=llm_config)

# Instrument the agent before use
tracer.instrument(assistant)

# Now run your agent normally
user_proxy.initiate_chat(assistant, message="Hello")"""

    elif framework == "crewai":
        return f"""from driftbase.integrations import CrewAITracer
from crewai import Crew, Agent, Task

# Create the tracer
tracer = CrewAITracer(version='{version}')

# Create your crew
crew = Crew(agents=[agent1, agent2], tasks=[task1, task2])

# Instrument the crew before kickoff
tracer.instrument(crew)

# Now run your crew normally
result = crew.kickoff()"""

    else:  # "other" - use generic @track decorator
        return f"""from driftbase import track

@track(version='{version}')
def {agent_function}(input_data):
    # Your agent logic here
    result = your_agent_code(input_data)
    return result

# Call your tracked function
output = {agent_function}(input_data)"""


def _print_snippet_with_highlighting(console: Console, code: str, use_color: bool) -> None:
    """Print code snippet with syntax highlighting if possible."""
    if not use_color:
        console.print("\n" + code + "\n")
        return

    try:
        from rich.syntax import Syntax
        syntax = Syntax(code, "python", theme="monokai", line_numbers=False)
        console.print()
        console.print(syntax)
        console.print()
    except ImportError:
        # Fallback to plain text
        console.print("\n" + code + "\n")


def _write_config_file(framework: str, version: str, agent_function: str) -> None:
    """Write configuration to ~/.driftbase/config.yml."""
    config_dir = Path.home() / ".driftbase"
    config_dir.mkdir(exist_ok=True)

    config_path = config_dir / "config.yml"

    config_content = f"""# Driftbase configuration (generated by driftbase init)
default_version: {version}
framework: {framework}
agent_function: {agent_function}
"""

    config_path.write_text(config_content)


@click.command(name="init")
@click.pass_context
def cmd_init(ctx: click.Context) -> None:
    """Interactive setup guide for Driftbase — get started in 60 seconds."""
    console: Console = ctx.obj["console"]
    use_color = not console.no_color

    # Welcome message
    if use_color:
        console.print()
        console.print(Panel(
            "[bold]Welcome to Driftbase![/]\n\n"
            "Driftbase tracks behavioral drift across agent versions.\n"
            "When you deploy a new prompt, model, or tool — Driftbase detects\n"
            "if your agent's behavior changed unexpectedly.\n\n"
            "[dim]This wizard will help you add tracking to your agent in 60 seconds.[/]",
            title="[bold cyan]🚀 Getting Started[/]",
            border_style="cyan",
        ))
        console.print()
    else:
        console.print("\n=== Welcome to Driftbase! ===\n")
        console.print("Driftbase tracks behavioral drift across agent versions.")
        console.print("When you deploy a new prompt, model, or tool — Driftbase detects")
        console.print("if your agent's behavior changed unexpectedly.\n")
        console.print("This wizard will help you add tracking to your agent in 60 seconds.\n")

    # Prompt 1: Framework
    console.print("[bold]Step 1/3: Which framework are you using?[/]" if use_color else "Step 1/3: Which framework are you using?")
    framework = click.prompt(
        "Framework",
        type=click.Choice(['langchain', 'langgraph', 'openai', 'autogen', 'crewai', 'other'], case_sensitive=False),
        default='other',
        show_choices=True,
    )

    # Prompt 2: Version
    console.print("\n[bold]Step 2/3: What is your baseline version?[/]" if use_color else "\nStep 2/3: What is your baseline version?")
    console.print("[dim]This is the version identifier for your current agent (e.g., v1.0, baseline, prod-2024-03)[/]" if use_color else "This is the version identifier for your current agent (e.g., v1.0, baseline, prod-2024-03)")
    version = click.prompt(
        "Version",
        type=str,
        default='v1.0',
    )

    # Prompt 3: Agent function name (only for "other")
    if framework == 'other':
        console.print("\n[bold]Step 3/3: What is your agent function name?[/]" if use_color else "\nStep 3/3: What is your agent function name?")
        console.print("[dim]The function you want to track (e.g., run_agent, process_request)[/]" if use_color else "The function you want to track (e.g., run_agent, process_request)")
        agent_function = click.prompt(
            "Function name",
            type=str,
            default='run_agent',
        )
    else:
        agent_function = 'run_agent'  # Not used for framework integrations
        console.print("\n[bold]Step 3/3: Configuration complete![/]" if use_color else "\nStep 3/3: Configuration complete!")

    # Generate code snippet
    code_snippet = _get_code_snippet(framework, version, agent_function)

    # Display the code snippet
    console.print()
    if use_color:
        console.print(Panel(
            "[bold]Copy and paste this code into your agent:[/]",
            border_style="green",
        ))
    else:
        console.print("=== Copy and paste this code into your agent: ===\n")

    _print_snippet_with_highlighting(console, code_snippet, use_color)

    # Write config file
    _write_config_file(framework, version, agent_function)
    config_path = Path.home() / ".driftbase" / "config.yml"

    if use_color:
        console.print(f"[dim]✓ Configuration saved to {config_path}[/]\n")
    else:
        console.print(f"✓ Configuration saved to {config_path}\n")

    # Print next steps checklist
    if use_color:
        console.print(Panel(
            "[bold]Next steps:[/]\n\n"
            "  [green]☐[/]  1. Add the code snippet above to your agent\n"
            "  [green]☐[/]  2. Run your agent at least 50 times to collect baseline data\n"
            "  [green]☐[/]  3. Verify runs are being captured:\n"
            f"       [cyan]driftbase runs --version {version}[/]\n"
            "  [green]☐[/]  4. After deploying a new version (e.g., v2.0), compare drift:\n"
            f"       [cyan]driftbase diff {version} v2.0[/]\n\n"
            "[dim]💡 Tip: Driftbase stores all data locally in ~/.driftbase/runs.db\n"
            "   No data leaves your machine unless you use --remote.[/]",
            title="[bold yellow]✓ Setup Complete![/]",
            border_style="yellow",
        ))
    else:
        console.print("=== Next steps: ===\n")
        console.print("  ☐  1. Add the code snippet above to your agent")
        console.print("  ☐  2. Run your agent at least 50 times to collect baseline data")
        console.print("  ☐  3. Verify runs are being captured:")
        console.print(f"       driftbase runs --version {version}")
        console.print("  ☐  4. After deploying a new version (e.g., v2.0), compare drift:")
        console.print(f"       driftbase diff {version} v2.0")
        console.print("\n💡 Tip: Driftbase stores all data locally in ~/.driftbase/runs.db")
        console.print("   No data leaves your machine unless you use --remote.\n")

    console.print()

    # Additional info based on framework
    if framework in ['langchain', 'langgraph']:
        if use_color:
            console.print("[dim]📚 LangChain/LangGraph users: The tracer is a standard BaseCallbackHandler.[/]")
            console.print("[dim]   You can also use it with LangSmith, it won't conflict.[/]\n")
        else:
            console.print("📚 LangChain/LangGraph users: The tracer is a standard BaseCallbackHandler.")
            console.print("   You can also use it with LangSmith, it won't conflict.\n")
    elif framework == 'openai':
        if use_color:
            console.print("[dim]📚 OpenAI users: The context manager patches calls only within the 'with' block.[/]")
            console.print("[dim]   Your existing code outside the block is unaffected.[/]\n")
        else:
            console.print("📚 OpenAI users: The context manager patches calls only within the 'with' block.")
            console.print("   Your existing code outside the block is unaffected.\n")

    if use_color:
        console.print("[bold green]Happy tracking! 🎯[/]\n")
    else:
        console.print("Happy tracking! 🎯\n")
