"""
Bookmark command: Save and run commonly used queries.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import click


def _safe_import_rich():
    try:
        from rich.console import Console
        from rich.table import Table

        return Console, Table
    except ImportError:
        return None, None


def _get_bookmarks_file() -> Path:
    """Get path to bookmarks file."""
    try:
        bookmark_file = Path.home() / ".driftbase" / "bookmarks.yaml"
    except Exception:
        bookmark_file = Path(".driftbase") / "bookmarks.yaml"
    return bookmark_file


def _load_bookmarks() -> dict[str, str]:
    """Load bookmarks from YAML file."""
    bookmark_file = _get_bookmarks_file()
    if not bookmark_file.exists():
        return {}

    try:
        import yaml

        with bookmark_file.open("r") as f:
            bookmarks = yaml.safe_load(f) or {}
            return bookmarks
    except ImportError:
        # Fallback to simple key=value format
        bookmarks = {}
        with bookmark_file.open("r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    bookmarks[key.strip()] = value.strip()
        return bookmarks
    except Exception:
        return {}


def _save_bookmarks(bookmarks: dict[str, str]) -> None:
    """Save bookmarks to YAML file."""
    bookmark_file = _get_bookmarks_file()
    bookmark_file.parent.mkdir(parents=True, exist_ok=True)

    try:
        import yaml

        with bookmark_file.open("w") as f:
            yaml.safe_dump(bookmarks, f, default_flow_style=False, sort_keys=True)
    except ImportError:
        # Fallback to simple key=value format
        with bookmark_file.open("w") as f:
            f.write("# Driftbase bookmarks\n")
            f.write("# Auto-generated by driftbase bookmark save\n\n")
            for name, command in sorted(bookmarks.items()):
                f.write(f"{name}={command}\n")


@click.group(name="bookmark")
def bookmark_group():
    """Save and run commonly used queries."""
    pass


@bookmark_group.command(name="save")
@click.argument("name")
@click.argument("command", nargs=-1, required=True)
@click.pass_context
def bookmark_save(ctx: click.Context, name: str, command: tuple[str, ...]):
    """
    Save a command as a bookmark.

    \b
    Examples:
      driftbase bookmark save prod-errors "runs -v production --errors-only"
      driftbase bookmark save weekly-diff "diff v1.0 v2.0 --since 7d"
      driftbase bookmark save slow-runs "runs -v v2.0 --slow --format json"
    """
    Console, Table = _safe_import_rich()
    console = ctx.obj.get("console") if Console else None

    if not console:
        console = type("PlainConsole", (), {"print": lambda self, x: print(x)})()

    # Join command parts
    command_str = " ".join(command)

    # Load existing bookmarks
    bookmarks = _load_bookmarks()

    # Check if bookmark exists
    if name in bookmarks:
        console.print(f"#FFA94D]⚠[/] Bookmark '{name}' already exists")
        console.print(f"  Current: {bookmarks[name]}")
        console.print(f"  New:     {command_str}")

        if not click.confirm("Overwrite?", default=False):
            console.print("[dim]Cancelled[/]")
            ctx.exit(0)

    # Save bookmark
    bookmarks[name] = command_str
    _save_bookmarks(bookmarks)

    console.print(f"#4ADE80]✓[/] Bookmark saved: #8B5CF6]{name}[/]")
    console.print(f"  Command: [dim]{command_str}[/]")
    console.print(f"\nRun with: #8B5CF6]driftbase bookmark run {name}[/]")

    ctx.exit(0)


@bookmark_group.command(name="run")
@click.argument("name")
@click.pass_context
def bookmark_run(ctx: click.Context, name: str):
    """
    Run a saved bookmark.

    \b
    Example:
      driftbase bookmark run prod-errors
    """
    Console, Table = _safe_import_rich()
    console = ctx.obj.get("console") if Console else None

    if not console:
        console = type("PlainConsole", (), {"print": lambda self, x: print(x)})()

    # Load bookmarks
    bookmarks = _load_bookmarks()

    if name not in bookmarks:
        console.print(f"#FF6B6B]✗[/] Bookmark '{name}' not found")
        console.print("\nAvailable bookmarks:")
        if bookmarks:
            for bookmark_name in sorted(bookmarks.keys()):
                console.print(f"  • {bookmark_name}")
        else:
            console.print("  [dim](none)[/]")
        ctx.exit(1)

    command_str = bookmarks[name]
    console.print(f"[dim]Running bookmark:[/] #8B5CF6]{name}[/]")
    console.print(f"[dim]Command:[/] driftbase {command_str}\n")

    # Execute the bookmark command
    try:
        result = subprocess.run(
            ["driftbase"] + command_str.split(),
            check=False,
        )
        ctx.exit(result.returncode)
    except Exception as e:
        console.print(f"#FF6B6B]Error:[/] Failed to run bookmark: {e}")
        ctx.exit(1)


@bookmark_group.command(name="list")
@click.pass_context
def bookmark_list(ctx: click.Context):
    """
    List all saved bookmarks.

    \b
    Example:
      driftbase bookmark list
    """
    Console, Table = _safe_import_rich()
    console = ctx.obj.get("console") if Console else None

    if not console:
        console = type("PlainConsole", (), {"print": lambda self, x: print(x)})()

    bookmarks = _load_bookmarks()

    if not bookmarks:
        console.print("#FFA94D]No bookmarks saved yet[/]")
        console.print("\nSave a bookmark with:")
        console.print('  #8B5CF6]driftbase bookmark save <name> "<command>"[/]')
        ctx.exit(0)

    console.print(f"\n[bold cyan]📑 Saved Bookmarks[/] ({len(bookmarks)})\n")

    if Table:
        table = Table(show_header=True, header_style="bold")
        table.add_column("Name", style="#8B5CF6")
        table.add_column("Command", style="dim")

        for name, command in sorted(bookmarks.items()):
            table.add_row(name, command)

        console.print(table)
    else:
        for name, command in sorted(bookmarks.items()):
            print(f"{name:20s} : {command}")

    console.print("\n[dim]Run with:[/] #8B5CF6]driftbase bookmark run <name>[/]\n")
    ctx.exit(0)


@bookmark_group.command(name="delete")
@click.argument("name")
@click.option("--yes", "-y", is_flag=True, help="Skip confirmation.")
@click.pass_context
def bookmark_delete(ctx: click.Context, name: str, yes: bool):
    """
    Delete a saved bookmark.

    \b
    Example:
      driftbase bookmark delete prod-errors
    """
    Console, Table = _safe_import_rich()
    console = ctx.obj.get("console") if Console else None

    if not console:
        console = type("PlainConsole", (), {"print": lambda self, x: print(x)})()

    bookmarks = _load_bookmarks()

    if name not in bookmarks:
        console.print(f"#FF6B6B]✗[/] Bookmark '{name}' not found")
        ctx.exit(1)

    command = bookmarks[name]

    if not yes:
        console.print(f"Delete bookmark: #8B5CF6]{name}[/]")
        console.print(f"  Command: [dim]{command}[/]")
        if not click.confirm("Are you sure?", default=False):
            console.print("[dim]Cancelled[/]")
            ctx.exit(0)

    del bookmarks[name]
    _save_bookmarks(bookmarks)

    console.print(f"#4ADE80]✓[/] Bookmark deleted: #8B5CF6]{name}[/]")
    ctx.exit(0)
