"""
Demo scenario templates, regression types, and framework-specific patterns.
This module provides reusable scenario definitions for driftbase demo command.
"""

from __future__ import annotations

from typing import Any, TypedDict


class ScenarioTemplate(TypedDict, total=False):
    """Template for a demo scenario"""

    weight: float
    tools: list[str]
    outcome: str
    p_tokens: tuple[int, int]
    c_tokens: tuple[int, int]
    latency: tuple[int, int]
    loop_count: tuple[int, int]
    retry_count: tuple[int, int]
    error_count: tuple[int, int]
    description: str


class RegressionType(TypedDict):
    """Defines a specific type of behavioral regression"""

    name: str
    description: str
    scenarios: list[ScenarioTemplate]
    expected_drift: dict[str, str]


class FrameworkTemplate(TypedDict):
    """Framework-specific agent patterns"""

    name: str
    description: str
    tools: list[str]
    baseline_scenarios: list[ScenarioTemplate]
    regression_scenarios: list[ScenarioTemplate]


# ============================================================================
# REGRESSION TYPE GALLERY
# ============================================================================

REGRESSION_TYPES: dict[str, RegressionType] = {
    "token-bloat": {
        "name": "Token Bloat",
        "description": "Agent produces wordier outputs without added value. Same functionality, higher costs.",
        "scenarios": [
            {
                "weight": 0.60,
                "tools": ["validate_input", "query_database", "format_response"],
                "outcome": "resolved",
                "p_tokens": (800, 1200),  # 2-3x baseline prompt tokens
                "c_tokens": (150, 300),  # 3-5x baseline completion tokens
                "latency": (350, 600),
                "loop_count": (1, 2),
                "retry_count": (0, 0),
                "description": "Simple query but with excessive verbosity",
            },
            {
                "weight": 0.30,
                "tools": [
                    "validate_input",
                    "query_database",
                    "summarize",
                    "format_response",
                ],
                "outcome": "resolved",
                "p_tokens": (900, 1400),
                "c_tokens": (180, 350),
                "latency": (450, 750),
                "loop_count": (2, 3),
                "retry_count": (0, 1),
                "description": "Added unnecessary summarization step",
            },
            {
                "weight": 0.10,
                "tools": [
                    "validate_input",
                    "query_database",
                    "retrieve_context",
                    "summarize",
                    "format_response",
                ],
                "outcome": "resolved",
                "p_tokens": (1000, 1500),
                "c_tokens": (200, 400),
                "latency": (550, 900),
                "loop_count": (2, 4),
                "retry_count": (0, 1),
                "description": "Excessive context retrieval + verbose formatting",
            },
        ],
        "expected_drift": {
            "verbosity_ratio": "HIGH (3-5x increase)",
            "cost": "HIGH (200-300% increase)",
            "latency": "MODERATE (20-40% increase)",
            "tool_sequence": "LOW (same tools, different token usage)",
        },
    },
    "loop-detection": {
        "name": "Loop Detection",
        "description": "Agent stuck in retry cycles or repetitive tool calls. Wastes tokens and time.",
        "scenarios": [
            {
                "weight": 0.50,
                "tools": [
                    "validate_input",
                    "query_database",
                    "query_database",
                    "query_database",
                    "format_response",
                ],
                "outcome": "resolved",
                "p_tokens": (900, 1300),
                "c_tokens": (80, 150),
                "latency": (1200, 2000),
                "loop_count": (5, 8),
                "retry_count": (3, 5),
                "description": "Repeated database queries without progress",
            },
            {
                "weight": 0.30,
                "tools": [
                    "validate_input",
                    "web_search",
                    "web_search",
                    "web_search",
                    "retrieve_context",
                    "query_database",
                ],
                "outcome": "resolved",
                "p_tokens": (1100, 1600),
                "c_tokens": (90, 160),
                "latency": (1500, 2500),
                "loop_count": (6, 10),
                "retry_count": (4, 7),
                "description": "Excessive web searches in loop",
            },
            {
                "weight": 0.20,
                "tools": [
                    "validate_input",
                    "check_permissions",
                    "check_permissions",
                    "query_database",
                    "check_permissions",
                    "escalate_to_human",
                ],
                "outcome": "escalated",
                "p_tokens": (1000, 1400),
                "c_tokens": (70, 130),
                "latency": (1400, 2200),
                "loop_count": (5, 9),
                "retry_count": (3, 6),
                "description": "Permission check loop before escalation",
            },
        ],
        "expected_drift": {
            "loop_count": "CRITICAL (5-10x increase)",
            "retry_count": "HIGH (3-7x increase)",
            "latency": "CRITICAL (3-5x increase)",
            "cost": "HIGH (2-3x increase)",
        },
    },
    "tool-dropout": {
        "name": "Tool Dropout",
        "description": "Critical tool no longer called. Agent lost capability or bypassing important step.",
        "scenarios": [
            {
                "weight": 0.60,
                "tools": ["validate_input", "query_database", "format_response"],
                "outcome": "resolved",
                "p_tokens": (400, 600),
                "c_tokens": (50, 90),
                "latency": (300, 500),
                "loop_count": (1, 2),
                "retry_count": (0, 0),
                "description": "Missing 'check_permissions' - security bypass",
            },
            {
                "weight": 0.25,
                "tools": ["validate_input", "query_database", "format_response"],
                "outcome": "resolved",
                "p_tokens": (450, 650),
                "c_tokens": (55, 95),
                "latency": (350, 550),
                "loop_count": (1, 2),
                "retry_count": (0, 1),
                "description": "Missing 'retrieve_context' - incomplete answers",
            },
            {
                "weight": 0.15,
                "tools": ["validate_input", "query_database", "escalate_to_human"],
                "outcome": "escalated",
                "p_tokens": (500, 700),
                "c_tokens": (40, 70),
                "latency": (400, 650),
                "loop_count": (2, 3),
                "retry_count": (0, 1),
                "description": "Skipped 'search_documents' - premature escalation",
            },
        ],
        "expected_drift": {
            "tool_sequence": "CRITICAL (key tool missing)",
            "tool_call_count": "MODERATE (20-40% reduction)",
            "decisions": "HIGH (escalation rate increase)",
            "correctness": "CRITICAL (bypassed validation/context)",
        },
    },
    "cost-explosion": {
        "name": "Cost Explosion",
        "description": "Same task consuming 3-5x more tokens. Often combined with loops and verbosity.",
        "scenarios": [
            {
                "weight": 0.40,
                "tools": [
                    "validate_input",
                    "query_database",
                    "web_search",
                    "retrieve_context",
                    "query_database",
                    "summarize",
                    "translate",
                    "format_response",
                ],
                "outcome": "resolved",
                "p_tokens": (1200, 1800),
                "c_tokens": (250, 450),
                "latency": (1500, 2500),
                "loop_count": (4, 7),
                "retry_count": (2, 4),
                "description": "Excessive tool chaining with translation overhead",
            },
            {
                "weight": 0.35,
                "tools": [
                    "validate_input",
                    "fetch_api",
                    "fetch_api",
                    "parse_json",
                    "query_database",
                    "web_search",
                    "retrieve_context",
                    "summarize",
                    "format_response",
                ],
                "outcome": "resolved",
                "p_tokens": (1400, 2000),
                "c_tokens": (300, 500),
                "latency": (1800, 3000),
                "loop_count": (5, 9),
                "retry_count": (3, 6),
                "description": "API calls + web fallback + verbose output",
            },
            {
                "weight": 0.25,
                "tools": [
                    "validate_input",
                    "query_database",
                    "retrieve_context",
                    "search_documents",
                    "web_search",
                    "calculate",
                    "summarize",
                    "translate",
                    "format_response",
                ],
                "outcome": "resolved",
                "p_tokens": (1600, 2200),
                "c_tokens": (350, 550),
                "latency": (2000, 3500),
                "loop_count": (6, 10),
                "retry_count": (4, 7),
                "description": "Kitchen sink approach - using all available tools",
            },
        ],
        "expected_drift": {
            "cost": "CRITICAL (300-500% increase)",
            "prompt_tokens": "CRITICAL (3-5x increase)",
            "completion_tokens": "CRITICAL (5-8x increase)",
            "tool_call_count": "HIGH (2-3x increase)",
        },
    },
    "latency-creep": {
        "name": "Latency Creep",
        "description": "Gradual performance degradation. Slower responses without obvious cause.",
        "scenarios": [
            {
                "weight": 0.50,
                "tools": [
                    "validate_input",
                    "query_database",
                    "retrieve_context",
                    "format_response",
                ],
                "outcome": "resolved",
                "p_tokens": (500, 700),
                "c_tokens": (60, 110),
                "latency": (1200, 1800),  # 3-4x baseline latency
                "loop_count": (2, 3),
                "retry_count": (0, 1),
                "description": "Slow database queries or network issues",
            },
            {
                "weight": 0.35,
                "tools": [
                    "validate_input",
                    "search_documents",
                    "retrieve_context",
                    "summarize",
                    "format_response",
                ],
                "outcome": "resolved",
                "p_tokens": (550, 750),
                "c_tokens": (70, 120),
                "latency": (1400, 2200),
                "loop_count": (2, 4),
                "retry_count": (1, 2),
                "description": "Document search taking longer",
            },
            {
                "weight": 0.15,
                "tools": [
                    "validate_input",
                    "fetch_api",
                    "parse_json",
                    "query_database",
                    "format_response",
                ],
                "outcome": "resolved",
                "p_tokens": (600, 800),
                "c_tokens": (65, 115),
                "latency": (1600, 2500),
                "loop_count": (2, 4),
                "retry_count": (1, 3),
                "description": "API timeout and retries",
            },
        ],
        "expected_drift": {
            "latency": "CRITICAL (3-5x increase)",
            "p95_latency": "CRITICAL (p95 >2000ms)",
            "time_to_first_tool": "HIGH (2-3x slower planning)",
            "cost": "LOW (latency not token-related)",
        },
    },
}


# ============================================================================
# FRAMEWORK-SPECIFIC TEMPLATES
# ============================================================================

FRAMEWORK_TEMPLATES: dict[str, FrameworkTemplate] = {
    "langgraph-rag": {
        "name": "LangGraph RAG Pipeline",
        "description": "Retrieval-Augmented Generation with LangGraph state machine",
        "tools": [
            "route_query",
            "embed_query",
            "vector_search",
            "rerank_results",
            "retrieve_documents",
            "build_context",
            "generate_response",
            "cite_sources",
        ],
        "baseline_scenarios": [
            {
                "weight": 0.70,
                "tools": [
                    "route_query",
                    "embed_query",
                    "vector_search",
                    "rerank_results",
                    "retrieve_documents",
                    "generate_response",
                    "cite_sources",
                ],
                "outcome": "resolved",
                "p_tokens": (600, 900),
                "c_tokens": (100, 180),
                "latency": (400, 700),
                "loop_count": (1, 2),
                "retry_count": (0, 0),
                "description": "Standard RAG pipeline: embed → search → rerank → generate",
            },
            {
                "weight": 0.20,
                "tools": [
                    "route_query",
                    "embed_query",
                    "vector_search",
                    "retrieve_documents",
                    "generate_response",
                ],
                "outcome": "resolved",
                "p_tokens": (450, 700),
                "c_tokens": (80, 140),
                "latency": (300, 550),
                "loop_count": (1, 2),
                "retry_count": (0, 0),
                "description": "Fast path: skip reranking for simple queries",
            },
            {
                "weight": 0.10,
                "tools": [
                    "route_query",
                    "embed_query",
                    "vector_search",
                    "rerank_results",
                    "retrieve_documents",
                    "build_context",
                    "generate_response",
                    "cite_sources",
                ],
                "outcome": "resolved",
                "p_tokens": (800, 1100),
                "c_tokens": (140, 220),
                "latency": (600, 1000),
                "loop_count": (2, 3),
                "retry_count": (0, 1),
                "description": "Complex query with explicit context building",
            },
        ],
        "regression_scenarios": [
            {
                "weight": 0.50,
                "tools": [
                    "route_query",
                    "embed_query",
                    "vector_search",
                    "vector_search",
                    "rerank_results",
                    "retrieve_documents",
                    "build_context",
                    "generate_response",
                    "cite_sources",
                ],
                "outcome": "resolved",
                "p_tokens": (1200, 1800),
                "c_tokens": (200, 350),
                "latency": (1000, 1800),
                "loop_count": (3, 5),
                "retry_count": (1, 3),
                "description": "Double vector search due to poor initial results",
            },
            {
                "weight": 0.30,
                "tools": [
                    "route_query",
                    "embed_query",
                    "vector_search",
                    "retrieve_documents",
                    "generate_response",
                ],
                "outcome": "resolved",
                "p_tokens": (900, 1300),
                "c_tokens": (150, 280),
                "latency": (700, 1200),
                "loop_count": (2, 3),
                "retry_count": (1, 2),
                "description": "Skipped reranking → poor quality → verbose compensatory output",
            },
            {
                "weight": 0.20,
                "tools": [
                    "route_query",
                    "embed_query",
                    "vector_search",
                    "rerank_results",
                    "retrieve_documents",
                    "build_context",
                    "build_context",
                    "generate_response",
                ],
                "outcome": "error",
                "p_tokens": (1400, 2000),
                "c_tokens": (100, 180),
                "latency": (1200, 2000),
                "loop_count": (4, 6),
                "retry_count": (2, 4),
                "error_count": (1, 2),
                "description": "Context building loop, eventual timeout",
            },
        ],
    },
    "autogen-research": {
        "name": "AutoGen Multi-Agent Research",
        "description": "Multi-agent system with planner, researcher, critic agents",
        "tools": [
            "plan_research",
            "assign_tasks",
            "web_search",
            "extract_facts",
            "cross_check",
            "critique_findings",
            "synthesize_report",
            "format_citations",
        ],
        "baseline_scenarios": [
            {
                "weight": 0.60,
                "tools": [
                    "plan_research",
                    "assign_tasks",
                    "web_search",
                    "extract_facts",
                    "cross_check",
                    "synthesize_report",
                    "format_citations",
                ],
                "outcome": "resolved",
                "p_tokens": (800, 1200),
                "c_tokens": (150, 250),
                "latency": (1000, 1600),
                "loop_count": (3, 5),
                "retry_count": (0, 1),
                "description": "Standard research flow: plan → search → verify → synthesize",
            },
            {
                "weight": 0.30,
                "tools": [
                    "plan_research",
                    "assign_tasks",
                    "web_search",
                    "extract_facts",
                    "critique_findings",
                    "web_search",
                    "synthesize_report",
                ],
                "outcome": "resolved",
                "p_tokens": (1000, 1500),
                "c_tokens": (180, 300),
                "latency": (1300, 2000),
                "loop_count": (4, 6),
                "retry_count": (1, 2),
                "description": "Critic agent requests additional research",
            },
            {
                "weight": 0.10,
                "tools": [
                    "plan_research",
                    "assign_tasks",
                    "web_search",
                    "extract_facts",
                    "synthesize_report",
                ],
                "outcome": "resolved",
                "p_tokens": (700, 1000),
                "c_tokens": (120, 200),
                "latency": (800, 1300),
                "loop_count": (2, 4),
                "retry_count": (0, 1),
                "description": "Simple research without critique loop",
            },
        ],
        "regression_scenarios": [
            {
                "weight": 0.40,
                "tools": [
                    "plan_research",
                    "assign_tasks",
                    "web_search",
                    "extract_facts",
                    "critique_findings",
                    "web_search",
                    "critique_findings",
                    "web_search",
                    "cross_check",
                    "synthesize_report",
                ],
                "outcome": "resolved",
                "p_tokens": (1800, 2600),
                "c_tokens": (300, 500),
                "latency": (2500, 4000),
                "loop_count": (8, 12),
                "retry_count": (3, 6),
                "description": "Excessive critique loop - agents can't agree",
            },
            {
                "weight": 0.35,
                "tools": [
                    "plan_research",
                    "assign_tasks",
                    "web_search",
                    "extract_facts",
                    "synthesize_report",
                ],
                "outcome": "resolved",
                "p_tokens": (1200, 1800),
                "c_tokens": (220, 400),
                "latency": (1500, 2400),
                "loop_count": (3, 5),
                "retry_count": (1, 2),
                "description": "Skipped cross-check → verbose compensatory synthesis",
            },
            {
                "weight": 0.25,
                "tools": [
                    "plan_research",
                    "assign_tasks",
                    "web_search",
                    "web_search",
                    "web_search",
                    "extract_facts",
                    "cross_check",
                ],
                "outcome": "error",
                "p_tokens": (1600, 2200),
                "c_tokens": (150, 250),
                "latency": (2200, 3500),
                "loop_count": (7, 10),
                "retry_count": (4, 7),
                "error_count": (1, 2),
                "description": "Planner stuck repeating search, never reaches synthesis",
            },
        ],
    },
    "crewai-customer-support": {
        "name": "CrewAI Customer Support",
        "description": "Multi-role crew for ticket classification, resolution, and escalation",
        "tools": [
            "classify_ticket",
            "check_knowledge_base",
            "query_order_status",
            "check_account_history",
            "draft_response",
            "sentiment_check",
            "escalate_to_human",
            "close_ticket",
        ],
        "baseline_scenarios": [
            {
                "weight": 0.65,
                "tools": [
                    "classify_ticket",
                    "check_knowledge_base",
                    "draft_response",
                    "sentiment_check",
                    "close_ticket",
                ],
                "outcome": "resolved",
                "p_tokens": (400, 650),
                "c_tokens": (80, 140),
                "latency": (350, 600),
                "loop_count": (1, 2),
                "retry_count": (0, 0),
                "description": "Standard resolution: classify → KB lookup → respond",
            },
            {
                "weight": 0.20,
                "tools": [
                    "classify_ticket",
                    "query_order_status",
                    "draft_response",
                    "close_ticket",
                ],
                "outcome": "resolved",
                "p_tokens": (350, 550),
                "c_tokens": (60, 110),
                "latency": (300, 500),
                "loop_count": (1, 2),
                "retry_count": (0, 0),
                "description": "Order inquiry fast path",
            },
            {
                "weight": 0.10,
                "tools": [
                    "classify_ticket",
                    "check_account_history",
                    "check_knowledge_base",
                    "draft_response",
                    "sentiment_check",
                    "escalate_to_human",
                ],
                "outcome": "escalated",
                "p_tokens": (500, 750),
                "c_tokens": (70, 120),
                "latency": (450, 750),
                "loop_count": (2, 3),
                "retry_count": (0, 1),
                "description": "Complex issue requiring human escalation",
            },
            {
                "weight": 0.05,
                "tools": [
                    "classify_ticket",
                    "check_knowledge_base",
                    "draft_response",
                ],
                "outcome": "error",
                "p_tokens": (400, 600),
                "c_tokens": (40, 80),
                "latency": (400, 650),
                "loop_count": (1, 2),
                "retry_count": (1, 2),
                "error_count": (1, 1),
                "description": "KB lookup failure",
            },
        ],
        "regression_scenarios": [
            {
                "weight": 0.30,
                "tools": [
                    "classify_ticket",
                    "check_knowledge_base",
                    "check_account_history",
                    "query_order_status",
                    "draft_response",
                    "sentiment_check",
                    "escalate_to_human",
                ],
                "outcome": "escalated",
                "p_tokens": (900, 1400),
                "c_tokens": (120, 220),
                "latency": (1000, 1700),
                "loop_count": (4, 6),
                "retry_count": (1, 3),
                "description": "Over-checking before escalation (lost confidence)",
            },
            {
                "weight": 0.35,
                "tools": [
                    "classify_ticket",
                    "check_knowledge_base",
                    "draft_response",
                    "sentiment_check",
                    "close_ticket",
                ],
                "outcome": "resolved",
                "p_tokens": (800, 1200),
                "c_tokens": (160, 300),
                "latency": (650, 1100),
                "loop_count": (2, 3),
                "retry_count": (0, 1),
                "description": "Same flow but excessively verbose responses",
            },
            {
                "weight": 0.20,
                "tools": [
                    "classify_ticket",
                    "draft_response",
                    "close_ticket",
                ],
                "outcome": "resolved",
                "p_tokens": (500, 750),
                "c_tokens": (90, 150),
                "latency": (400, 650),
                "loop_count": (1, 2),
                "retry_count": (0, 0),
                "description": "Skipped KB check → incomplete answers",
            },
            {
                "weight": 0.15,
                "tools": [
                    "classify_ticket",
                    "check_knowledge_base",
                    "check_knowledge_base",
                    "draft_response",
                    "sentiment_check",
                ],
                "outcome": "error",
                "p_tokens": (700, 1000),
                "c_tokens": (80, 140),
                "latency": (1100, 1800),
                "loop_count": (3, 5),
                "retry_count": (2, 4),
                "error_count": (1, 2),
                "description": "KB lookup loop, timeout before closure",
            },
        ],
    },
    "code-generation": {
        "name": "Code Generation Agent",
        "description": "Understand requirements → plan → implement → test cycle",
        "tools": [
            "parse_requirements",
            "search_codebase",
            "analyze_dependencies",
            "plan_implementation",
            "generate_code",
            "run_tests",
            "fix_errors",
            "format_code",
        ],
        "baseline_scenarios": [
            {
                "weight": 0.50,
                "tools": [
                    "parse_requirements",
                    "search_codebase",
                    "plan_implementation",
                    "generate_code",
                    "run_tests",
                    "format_code",
                ],
                "outcome": "resolved",
                "p_tokens": (1000, 1500),
                "c_tokens": (300, 500),
                "latency": (1500, 2500),
                "loop_count": (2, 3),
                "retry_count": (0, 1),
                "description": "Clean implementation: plan → code → test → success",
            },
            {
                "weight": 0.35,
                "tools": [
                    "parse_requirements",
                    "search_codebase",
                    "analyze_dependencies",
                    "plan_implementation",
                    "generate_code",
                    "run_tests",
                    "fix_errors",
                    "run_tests",
                    "format_code",
                ],
                "outcome": "resolved",
                "p_tokens": (1400, 2000),
                "c_tokens": (400, 650),
                "latency": (2000, 3200),
                "loop_count": (3, 5),
                "retry_count": (1, 2),
                "description": "One test failure fixed",
            },
            {
                "weight": 0.15,
                "tools": [
                    "parse_requirements",
                    "search_codebase",
                    "plan_implementation",
                    "generate_code",
                    "run_tests",
                    "fix_errors",
                    "run_tests",
                    "fix_errors",
                    "run_tests",
                ],
                "outcome": "error",
                "p_tokens": (1600, 2300),
                "c_tokens": (350, 550),
                "latency": (2500, 4000),
                "loop_count": (4, 7),
                "retry_count": (2, 4),
                "error_count": (1, 2),
                "description": "Multiple test failures, eventual timeout",
            },
        ],
        "regression_scenarios": [
            {
                "weight": 0.40,
                "tools": [
                    "parse_requirements",
                    "search_codebase",
                    "search_codebase",
                    "analyze_dependencies",
                    "plan_implementation",
                    "generate_code",
                    "run_tests",
                    "fix_errors",
                    "run_tests",
                    "fix_errors",
                    "run_tests",
                    "fix_errors",
                    "run_tests",
                ],
                "outcome": "error",
                "p_tokens": (2500, 3500),
                "c_tokens": (500, 850),
                "latency": (4000, 6500),
                "loop_count": (8, 12),
                "retry_count": (4, 8),
                "error_count": (2, 4),
                "description": "Excessive test-fix loop, never converges",
            },
            {
                "weight": 0.35,
                "tools": [
                    "parse_requirements",
                    "plan_implementation",
                    "generate_code",
                    "run_tests",
                    "fix_errors",
                    "run_tests",
                ],
                "outcome": "resolved",
                "p_tokens": (1800, 2600),
                "c_tokens": (450, 750),
                "latency": (2200, 3600),
                "loop_count": (3, 5),
                "retry_count": (1, 3),
                "description": "Skipped codebase search → incorrect implementation → test failures",
            },
            {
                "weight": 0.25,
                "tools": [
                    "parse_requirements",
                    "search_codebase",
                    "plan_implementation",
                    "generate_code",
                    "format_code",
                ],
                "outcome": "resolved",
                "p_tokens": (1200, 1800),
                "c_tokens": (350, 600),
                "latency": (1600, 2600),
                "loop_count": (2, 3),
                "retry_count": (0, 1),
                "description": "Skipped testing → shipped without validation",
            },
        ],
    },
}


# ============================================================================
# INDUSTRY BENCHMARKS
# ============================================================================

INDUSTRY_BENCHMARKS = {
    "rag-pipeline": {
        "name": "RAG Pipeline (Industry Average)",
        "description": "Typical retrieval-augmented generation performance",
        "metrics": {
            "p50_latency": 450,
            "p95_latency": 800,
            "p99_latency": 1200,
            "avg_prompt_tokens": 650,
            "avg_completion_tokens": 120,
            "tool_call_count": 5,
            "error_rate": 0.02,
            "escalation_rate": 0.03,
        },
    },
    "customer-support": {
        "name": "Customer Support Bot (Industry Average)",
        "description": "Typical automated customer support performance",
        "metrics": {
            "p50_latency": 350,
            "p95_latency": 650,
            "p99_latency": 1000,
            "avg_prompt_tokens": 450,
            "avg_completion_tokens": 90,
            "tool_call_count": 4,
            "error_rate": 0.03,
            "escalation_rate": 0.12,
        },
    },
    "code-generation": {
        "name": "Code Generation Agent (Industry Average)",
        "description": "Typical code generation performance",
        "metrics": {
            "p50_latency": 2000,
            "p95_latency": 4500,
            "p99_latency": 7000,
            "avg_prompt_tokens": 1500,
            "avg_completion_tokens": 450,
            "tool_call_count": 6,
            "error_rate": 0.08,
            "escalation_rate": 0.05,
        },
    },
    "research-agent": {
        "name": "Research Agent (Industry Average)",
        "description": "Typical multi-agent research performance",
        "metrics": {
            "p50_latency": 1200,
            "p95_latency": 2500,
            "p99_latency": 4000,
            "avg_prompt_tokens": 1000,
            "avg_completion_tokens": 200,
            "tool_call_count": 6,
            "error_rate": 0.04,
            "escalation_rate": 0.08,
        },
    },
}


# ============================================================================
# COST MODELS
# ============================================================================

COST_MODELS = {
    "enterprise": {
        "name": "Enterprise (Volume Discount)",
        "description": "Negotiated enterprise rates with volume discount",
        "rate_prompt_1m": 1.80,  # €1.80 per 1M prompt tokens
        "rate_completion_1m": 7.50,  # €7.50 per 1M completion tokens
    },
    "standard": {
        "name": "Standard (List Price)",
        "description": "OpenAI list prices for GPT-4",
        "rate_prompt_1m": 2.50,
        "rate_completion_1m": 10.00,
    },
    "budget": {
        "name": "Budget (GPT-3.5)",
        "description": "Cost-optimized with GPT-3.5 Turbo",
        "rate_prompt_1m": 0.50,
        "rate_completion_1m": 1.50,
    },
}
